server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: book-subscription-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: 123456
    sql-script-encoding: UTF-8
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
        log4j2:
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 禁用Spring Security自动配置
autoconfigure:
  exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.library.subscription.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.library.subscription: debug
    org.springframework: warn

swagger:
  enabled: true
  title: 图书管理系统API文档
  description: 图书管理系统接口文档
  version: 1.0
  contact:
    name: Admin
    url: http://localhost:8080
    email: admin@example.com
sql:
  init:
    mode: always
    schema-locations: classpath:db/init-schema.sql
    data-locations: classpath:db/init-data.sql
